[package]
name = "rvmasm-legacy"
version = "1.8.1"
edition = "2024"
tags = ["assembler", "vm", "virtual machine"]
license = "MIT"
description = "Assembler for RvmASM"
readme = "README.md"

[dependencies]
colored = "3.0.0"
